name: Build Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
    - name: Prepare gradle cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
       
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport

    - uses: actions/upload-artifact@v2
      with:
        name: check-style-reports
        path: |
          ${{ github.workspace }}/validator-boot-example/build/reports/checkstyle/
          ${{ github.workspace }}/validator-boot-example/build/reports/checkstyle/

    - name: Static Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_ORG:  ${{ secrets.SONAR_ORG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew sonarqube